name: Run acceptance test

on:
    pull_request_target:
         types: [opened, synchronize, reopened]
         branches: [ main ]

jobs:
    build:
        name: Build artifacts
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  path: "chart-verifier"

            - name: Set up Python 3.x
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'

            - name: Set up Python scripts on PR branch
              working-directory: ./chart-verifier
              run: |
                  # set up python requirements and scripts on PR branch
                  python3 -m venv ve1
                  cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
                  cd scripts && ../ve1/bin/python3 setup.py install && cd ..

            - name: Get Date
              id: get-date
              run: |
                  echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
              shell: bash

            - uses: actions/cache@v2
              id: cache
              with:
                path: ./chart-verifier/oc
                key: ${{ steps.get-date.outputs.date }}

            - name: Install oc
              working-directory: ./chart-verifier
              id: install-oc
              run: |
                  # install oc
                  curl -sLO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
                  tar zxvf openshift-client-linux.tar.gz oc

            - name: Build the Image
              working-directory: ./chart-verifier
              id: build_image
              run: |
                    # build a docker image
                    commit_sha=$(git rev-parse --short HEAD)
                    ve1/bin/build-and-test --image-name="quay.io/redhat-certification/chart-verifier" --sha-value=$commit_sha --build-only="True"}

            - name: Login to oc
              working-directory: ./chart-verifier
              env:
                  KUBECONFIG: /tmp/ci-kubeconfig
              run: |
                  # oc login
                  API_SERVER=$( echo -n ${{ secrets.API_SERVER }} | base64 -d)
                  gpg --version
                  curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
                  if [ $GITHUB_REPOSITORY == "redhat-certification/chart-verifier" ]; then
                    ./oc login --token=${{ secrets.CLUSTER_TOKEN }} --server=${API_SERVER}
                  else
                    ./oc login --insecure-skip-tls-verify --token=${{ secrets.CLUSTER_TOKEN }} --server=${API_SERVER}
                  fi
                  ve1/bin/sa-for-chart-testing --create charts-${{ github.event.number }} --token token.txt --server ${API_SERVER}

            - name: Run the tests
              working-directory: ./chart-verifier
              env:
                  KUBECONFIG: /tmp/ci-kubeconfig
                  VERIFIER_IMAGE_TAG:  ${{ steps.build_image.outputs.verifier-image-tag }}
              id: run_tetst
              run: |
                   # run pytest
                   ve1/bin/pytest -v --log-cli-level=WARNING --tb=short

            - name: Delete Namespace
              if: ${{ steps.install-oc.outputs.oc-installed == 'true' }}
              working-directory: ./chart-verifier
              env:
                  KUBECONFIG: /tmp/ci-kubeconfig
              run: |
                  # delete the namespace
                  API_SERVER=$( echo -n ${{ secrets.API_SERVER }} | base64 -d)
                  ./oc login --token=${{ secrets.CLUSTER_TOKEN }} --server=${API_SERVER}
                  ve1/bin/sa-for-chart-testing --delete charts-${{ github.event.number }}

